include classpath("application.conf")

node-address {
  protocol = http
  host = "*"
  port = 9324
  context-path = ""
}

rest-sqs {
  enabled = true
  bind-port = 9324
  bind-hostname = "0.0.0.0"
}

aws {
  region = ap-southeast-1
  accountId = "000000000000"
}

queues {
  sync-queue {
    defaultVisibilityTimeout = 30 seconds
    delay = 0 seconds
    receiveMessageWait = 10 seconds
  }
}

messages-storage {
  enabled = true
}